### ISSUE TITLE
Igrica na OSX

### ISSUE THREAD

**Issue by andrejbauer** [lpolajzar/Spomin#3]
1. Odpre se mi malce premajhno okno, ne vidi se desnega roba in spodnje vrstice z besedilom, glej sliko spodaj.
2. Vse slike so sive, verjetno zaradi tega, ker delaš gumbe s `state = DISABLED` v funkciji `callback`. Če to odstranim, se slike v redu.
3. Full se stvari izpisuje v terminalsko okno.

![spomin](https://cloud.githubusercontent.com/assets/646599/6887833/85ad94c4-d66b-11e4-9275-41f943a42ca3.png)

**Comment by lpolajzar** [comment]
1. Sem spremenila, da velikost okna ni več fiksna.
2. Moralo bi biti state = DISABLED komaj ko najde par - popravljeno.
3. Printi so mi bili v pomoč pri programiranju - zaenkrat jih bom zakomentirala, če bi mi še kaj prišli prav.
